Update quectel-timesync

diff --git a/openwrt/quectel-timesync/files/etc/init.d/quectel-timesync b/openwrt/quectel-timesync/files/etc/init.d/quectel-timesync
--- a/openwrt/quectel-timesync/files/etc/init.d/quectel-timesync
+++ b/openwrt/quectel-timesync/files/etc/init.d/quectel-timesync
@@ -4,23 +4,22 @@ USE_PROCD=1
 
 PROG=/usr/sbin/quectel-timesync
 
-validate_section() {
-   uci_validate_section quectel-timesync main \
+start_service() {
+    . /lib/functions.sh
+
+    uci_validate_section quectel-timesync main \
         'enabled:bool:0' \
         'path:string' \
-        'interval:uinteger:3600'
-}
+        'interval:uinteger:3600' || return 1
 
-start_service() {
-   validate_section || return 1
-   [ "$enabled" = "1" ] || return 1
+    [ "$enabled" = "1" ] || return 1
 
-   if [ -z "$path" ]; then
-       logger -t quectel-timesync "ERROR: 'path' not set in /etc/config/quectel-timesync"
-       return 1
-   fi
+    if [ -z "$path" ]; then
+        logger -t quectel-timesync "ERROR: 'path' not set in /etc/config/quectel-timesync"
+        return 1
+    fi
 
-   procd_open_instance
-   procd_set_param command $PROG -d "$interval" -p "$path"
-   procd_close_instance
+    procd_open_instance
+    procd_set_param command $PROG -d "$interval" -p "$path"
+    procd_close_instance
 }
